use super::common::*;
use crate::analysis::build_logic_graphs;
use crate::decode::pins::{consume_known_node_tail, is_editable_pin_class};
use crate::decode::{DecodeReport, DecodedExport, DecodedExportIdentity};
use crate::model::EdgeKind;
use crate::name::NameMap;
use crate::output::OutputSections;
use crate::package::Package;
use crate::pin::{
    Pin, PinSerCtx, container_type_label, direction_label, is_supported_framework_pin_version,
    locate_legacy_pin_start, parse_node_pins, parse_node_pins_report, parse_pin_ref_array,
    parse_user_defined_pins_report,
};
use crate::property::{ParseCtx, parse_properties};
use crate::reader::{Guid, Reader};

#[test]
fn node_pin_array_decodes() {
    let names = NameMap {
        names: vec![
            "MyPin".to_string(),
            "exec".to_string(),
            "None".to_string(),
            "MemberFunc".to_string(),
        ],
    };

    let mut d = Vec::new();

    push_i32(&mut d, 0); // PossiblySerializeObjectGuid presence = false

    push_i32(&mut d, 1); // pin count

    // Owning-pin element prelude: null flag + wrapper node index + wrapper pin guid.

    push_i32(&mut d, 0);

    push_i32(&mut d, 3);

    push_guid(&mut d, 1, 2, 3, 4);

    // Pin body (filter_editor_only = false, no source index, no wrapper flags).

    push_i32(&mut d, 3); // owning node

    push_guid(&mut d, 1, 2, 3, 4); // pin id

    push_raw_name(&mut d, 0); // MyPin

    push_empty_ftext(&mut d); // friendly name

    push_fstring(&mut d, ""); // tooltip

    d.push(1); // direction = output

    push_raw_name(&mut d, 1); // pin type category "exec"

    push_raw_name(&mut d, 2); // pin type sub_category

    push_i32(&mut d, 0); // sub_category_object

    d.push(0); // container type = none

    push_i32(&mut d, 1); // bIsReference

    push_i32(&mut d, 1); // bIsWeakPointer

    push_i32(&mut d, -4); // member reference parent

    push_raw_name(&mut d, 3); // member reference name

    push_guid(&mut d, 4, 3, 2, 1); // member reference guid

    push_i32(&mut d, 1); // bIsConst

    push_i32(&mut d, 1); // bIsUObjectWrapper

    push_i32(&mut d, 1); // bSerializeAsSinglePrecisionFloat

    push_fstring(&mut d, ""); // default value

    push_fstring(&mut d, ""); // autogenerated default

    push_i32(&mut d, 0); // default object

    push_empty_ftext(&mut d); // default text

    push_i32(&mut d, 1); // LinkedTo count

    push_i32(&mut d, 0); // reference: not null

    push_i32(&mut d, 2); // referenced node index

    push_guid(&mut d, 9, 9, 9, 9); // referenced pin guid

    push_i32(&mut d, 0); // SubPins count

    push_i32(&mut d, 1); // parent pin = null

    push_i32(&mut d, 0); // reference passthrough = not null

    push_i32(&mut d, 5); // pass-through node index

    push_guid(&mut d, 8, 8, 8, 8); // pass-through pin guid

    push_guid(&mut d, 6, 7, 8, 9); // persistent guid (editor-only block)

    push_u32(&mut d, (1 << 0) | (1 << 3) | (1 << 5)); // editor bitfield

    let ctx = ParseCtx {
        names: &names,

        resolve_object: &|_idx: i32| serde_json::Value::Null,

        pins: PinSerCtx::default(),

        soft_object_paths: &[],

        serialization: crate::version::SerializationPolicy::default(),

        file_version_ue4: crate::version::ue4::HIGHEST,

        file_version_ue5: crate::version::ue5::PROPERTY_TAG_COMPLETE_TYPE_NAME,
    };

    let vc = PinSerCtx {
        has_uobject_wrapper: true,

        has_single_precision_float: true,

        ..PinSerCtx::default()
    };

    let mut r = Reader::new(&d);

    let pins = parse_node_pins(&mut r, d.len() as u64, &ctx, &vc).expect("pins should parse");

    assert_eq!(r.pos(), d.len() as u64, "pin array must consume all bytes");

    assert_eq!(pins.len(), 1);

    let p = &pins[0];

    assert_eq!(p.name, "MyPin");

    assert!(p.friendly_name.is_some());

    assert_eq!(p.source_index, None);

    assert_eq!(p.tooltip, "");

    assert_eq!(p.autogenerated_default_value, "");

    assert_eq!(direction_label(p.direction), "output");

    assert_eq!(p.category, "exec");

    assert_eq!(container_type_label(p.container_type), "none");

    assert!(p.is_reference);

    assert!(p.is_weak_pointer);

    assert_eq!(p.member_parent, -4);

    assert_eq!(p.member_name, "MemberFunc");

    assert_eq!(p.member_guid.to_hex(), "00000004000000030000000200000001");

    assert!(p.is_const);

    assert!(p.is_uobject_wrapper);

    assert!(p.serialize_as_single_precision_float);

    assert_eq!(p.pin_id.to_hex(), "00000001000000020000000300000004");

    assert_eq!(p.linked_to.len(), 1);

    assert_eq!(p.linked_to[0].node_index, 2);

    assert!(p.sub_pins.is_empty());

    assert!(p.parent_pin.is_none());

    let pass_through = p.reference_pass_through.as_ref().unwrap();

    assert_eq!(pass_through.node_index, 5);

    assert_eq!(
        pass_through.pin_id.to_hex(),
        "00000008000000080000000800000008"
    );

    assert_eq!(
        p.persistent_guid.unwrap().to_hex(),
        "00000006000000070000000800000009"
    );

    let flags = p.editor_flags.as_ref().unwrap();

    assert!(flags.hidden);

    assert!(!flags.not_connectable);

    assert!(!flags.default_value_read_only);

    assert!(flags.default_value_ignored);

    assert!(!flags.advanced_view);

    assert!(flags.orphaned_pin);
}

#[test]
fn node_pin_parse_failure_reports_diagnostic() {
    let names = NameMap {
        names: vec!["None".to_string()],
    };
    let mut d = Vec::new();
    push_i32(&mut d, 0); // no UObject guid
    push_i32(&mut d, 10_000); // invalid pin count

    let ctx = ParseCtx {
        names: &names,
        resolve_object: &|_idx: i32| serde_json::Value::Null,
        pins: PinSerCtx::default(),
        soft_object_paths: &[],
        serialization: crate::version::SerializationPolicy::default(),
        file_version_ue4: crate::version::ue4::HIGHEST,
        file_version_ue5: crate::version::ue5::PROPERTY_TAG_COMPLETE_TYPE_NAME,
    };

    let mut r = Reader::new(&d);
    let err = parse_node_pins_report(
        &mut r,
        d.len() as u64,
        &ctx,
        &PinSerCtx::default(),
        "/exports/0/pins",
    )
    .expect_err("invalid pin stream should report a diagnostic");

    assert_eq!(err.code, "pin_parse_failed");
    assert_eq!(err.path, "/exports/0/pins");
    assert!(err.message.contains("pin count out of range"));
    assert_eq!(err.offset, Some(8));
    assert_eq!(r.pos(), 0, "failed pin parse must rewind to start");
}

#[test]
fn edgraph_pin_type_map_container_decodes() {
    // Map-container pin types carry an FEdGraphTerminalType (map value type) between

    // ContainerType and bIsReference.

    let names = NameMap {
        names: vec![
            "PinType".to_string(),        // 0
            "StructProperty".to_string(), // 1
            "EdGraphPinType".to_string(), // 2
            "int".to_string(),            // 3
            "string".to_string(),         // 4
            "None".to_string(),           // 5
        ],
    };

    let mut value = Vec::new();

    push_raw_name(&mut value, 3); // category = "int"

    push_raw_name(&mut value, 5); // sub_category

    push_i32(&mut value, -4); // sub_category_object

    value.push(3); // container_type = Map

    push_raw_name(&mut value, 4); // terminal category = "string"

    push_raw_name(&mut value, 5); // terminal sub_category

    push_i32(&mut value, 0); // terminal sub_category_object

    push_i32(&mut value, 1); // terminal bIsConst

    push_i32(&mut value, 1); // terminal bIsWeakPointer

    push_i32(&mut value, 1); // terminal bIsUObjectWrapper (wrapper flag enabled)

    push_i32(&mut value, 1); // bIsReference

    push_i32(&mut value, 1); // bIsWeakPointer

    push_i32(&mut value, -8); // member reference parent

    push_raw_name(&mut value, 4); // member reference name

    push_guid(&mut value, 1, 1, 2, 2); // member reference guid

    push_i32(&mut value, 1); // bIsConst

    push_i32(&mut value, 1); // bIsUObjectWrapper

    push_i32(&mut value, 1); // bSerializeAsSinglePrecisionFloat

    let d = build_struct_property(2, 5, &value);

    let ctx = ParseCtx {
        names: &names,

        resolve_object: &|idx: i32| serde_json::json!({ "index": idx }),

        pins: PinSerCtx {
            filter_editor_only: false,

            has_source_index: false,

            has_uobject_wrapper: true,

            has_single_precision_float: true,
        },

        soft_object_paths: &[],

        serialization: crate::version::SerializationPolicy::default(),

        file_version_ue4: crate::version::ue4::HIGHEST,

        file_version_ue5: crate::version::ue5::PROPERTY_TAG_COMPLETE_TYPE_NAME,
    };

    let mut r = Reader::new(&d);

    let entries = parse_properties(&mut r, &ctx, d.len() as u64);

    assert_eq!(entries.len(), 1);

    let v = &entries[0].value;

    assert_eq!(v["category"].as_str(), Some("int"));

    assert_eq!(v["sub_category_object"]["index"].as_i64(), Some(-4));

    assert_eq!(v["container_type"].as_str(), Some("map"));

    assert_eq!(v["value_type"]["category"].as_str(), Some("string"));

    assert_eq!(v["value_type"]["is_const"].as_bool(), Some(true));

    assert_eq!(v["value_type"]["is_weak_pointer"].as_bool(), Some(true));

    assert_eq!(v["value_type"]["is_uobject_wrapper"].as_bool(), Some(true));

    assert_eq!(v["is_reference"].as_bool(), Some(true));

    assert_eq!(v["is_weak_pointer"].as_bool(), Some(true));

    assert_eq!(v["member_reference"]["parent"]["index"].as_i64(), Some(-8));

    assert_eq!(v["member_reference"]["name"].as_str(), Some("string"));

    assert_eq!(
        v["member_reference"]["guid"].as_str(),
        Some("00000001000000010000000200000002")
    );

    assert_eq!(v["is_const"].as_bool(), Some(true));

    assert_eq!(v["is_uobject_wrapper"].as_bool(), Some(true));

    assert_eq!(
        v["serialize_as_single_precision_float"].as_bool(),
        Some(true)
    );
}

#[test]
fn legacy_property_terminator_locates_the_same_pin_stream_as_script_offset() {
    let names = NameMap {
        names: vec!["MyPin".into(), "exec".into(), "None".into()],
    };
    let mut data = Vec::new();
    push_raw_name(&mut data, 2); // legacy property-list None terminator
    let explicit_pin_start = data.len() as u64;
    push_minimal_owned_pin(&mut data);

    let pin_context = PinSerCtx {
        filter_editor_only: true,
        ..PinSerCtx::default()
    };
    let legacy_context = ParseCtx {
        names: &names,
        resolve_object: &|_| serde_json::Value::Null,
        pins: pin_context,
        soft_object_paths: &[],
        serialization: crate::version::SerializationPolicy::default(),
        file_version_ue4: crate::version::ue4::HIGHEST,
        file_version_ue5: 1009,
    };
    let script_offset_context = ParseCtx {
        file_version_ue5: 1010,
        ..legacy_context
    };

    let mut legacy_reader = Reader::new(&data);
    let located = locate_legacy_pin_start(
        &mut legacy_reader,
        data.len() as u64,
        &legacy_context,
        "/exports/0/pins",
    )
    .expect("legacy None terminator must establish the pin boundary");
    assert_eq!(located, explicit_pin_start);
    let legacy_pins = parse_node_pins(
        &mut legacy_reader,
        data.len() as u64,
        &legacy_context,
        &pin_context,
    )
    .expect("legacy pins should parse");

    let mut script_offset_reader = Reader::new(&data);
    script_offset_reader.seek(explicit_pin_start).unwrap();
    let script_offset_pins = parse_node_pins(
        &mut script_offset_reader,
        data.len() as u64,
        &script_offset_context,
        &pin_context,
    )
    .expect("script-offset pins should parse");

    assert_eq!(legacy_pins.len(), 1);
    assert_eq!(legacy_pins[0].pin_id, script_offset_pins[0].pin_id);
    assert_eq!(legacy_pins[0].name, script_offset_pins[0].name);
    assert_eq!(legacy_pins[0].category, script_offset_pins[0].category);
}

#[test]
fn legacy_pin_boundary_is_not_guessed_without_none_terminator() {
    let names = NameMap {
        names: vec!["Value".into(), "IntProperty".into(), "None".into()],
    };
    let mut data = Vec::new();
    push_legacy_tag_header(&mut data, 0, 1, 4);
    push_legacy_tag_tail(&mut data);
    push_i32(&mut data, 7);
    let context = ParseCtx {
        names: &names,
        resolve_object: &|_| serde_json::Value::Null,
        pins: PinSerCtx::default(),
        soft_object_paths: &[],
        serialization: crate::version::SerializationPolicy::default(),
        file_version_ue4: crate::version::ue4::HIGHEST,
        file_version_ue5: 1009,
    };
    let mut reader = Reader::new(&data);
    let diagnostic =
        locate_legacy_pin_start(&mut reader, data.len() as u64, &context, "/exports/0/pins")
            .expect_err("a property list without None must not produce a pin offset");
    assert_eq!(diagnostic.code, "legacy_pin_property_boundary_unavailable");
    assert_eq!(reader.pos(), 0);
}

#[test]
fn user_defined_pins_follow_framework_name_layout() {
    let names = NameMap {
        names: vec!["UserParam".into(), "real".into(), "None".into()],
    };
    let context = ParseCtx {
        names: &names,
        resolve_object: &|_| serde_json::Value::Null,
        pins: PinSerCtx::default(),
        soft_object_paths: &[],
        serialization: crate::version::SerializationPolicy::default(),
        file_version_ue4: crate::version::ue4::HIGHEST,
        file_version_ue5: 1017,
    };

    let mut fname_data = Vec::new();
    push_i32(&mut fname_data, 1);
    push_raw_name(&mut fname_data, 0);
    push_minimal_pin_type(&mut fname_data, 1, 2);
    fname_data.push(0);
    push_fstring(&mut fname_data, "12.5");
    let mut fname_reader = Reader::new(&fname_data);
    let fname_pins = parse_user_defined_pins_report(
        &mut fname_reader,
        fname_data.len() as u64,
        &context,
        &PinSerCtx::default(),
        37,
        "/exports/0/pins/user_defined",
    )
    .expect("current Framework layout should parse");
    assert_eq!(fname_reader.pos(), fname_data.len() as u64);
    assert_eq!(fname_pins[0].name, "UserParam");
    assert_eq!(fname_pins[0].pin_type.category, "real");
    assert_eq!(fname_pins[0].default_value, "12.5");

    let mut string_data = Vec::new();
    push_i32(&mut string_data, 1);
    push_fstring(&mut string_data, "LegacyParam");
    push_minimal_pin_type(&mut string_data, 1, 2);
    string_data.push(1);
    push_fstring(&mut string_data, "");
    let mut string_reader = Reader::new(&string_data);
    let string_pins = parse_user_defined_pins_report(
        &mut string_reader,
        string_data.len() as u64,
        &context,
        &PinSerCtx::default(),
        30,
        "/exports/0/pins/user_defined",
    )
    .expect("legacy Framework layout should parse FString names");
    assert_eq!(string_reader.pos(), string_data.len() as u64);
    assert_eq!(string_pins[0].name, "LegacyParam");
    assert!(!is_supported_framework_pin_version(38));
}

#[test]
fn editable_pin_descendants_include_bound_events_and_macro_nodes() {
    for class in [
        "/Script/BlueprintGraph.K2Node_ComponentBoundEvent",
        "/Script/BlueprintGraph.K2Node_MacroInstance",
        "/Script/BlueprintGraph.K2Node_Composite",
        "/Script/EnhancedInputEditor.K2Node_EnhancedInputActionEvent",
    ] {
        assert!(
            is_editable_pin_class(class),
            "{class} must consume FUserPinInfo"
        );
    }
    assert!(!is_editable_pin_class(
        "/Script/BlueprintGraph.K2Node_DynamicCast"
    ));
}

#[test]
fn dynamic_cast_pure_state_tail_is_version_gated_and_bounded() {
    let names = NameMap { names: Vec::new() };
    let serialization = crate::version::SerializationPolicy {
        fortnite_main_version: crate::version::custom::DYNAMIC_CAST_NODES_USE_PURE_STATE_ENUM,
        ..Default::default()
    };
    let context = ParseCtx {
        names: &names,
        resolve_object: &|_| serde_json::Value::Null,
        pins: PinSerCtx::default(),
        soft_object_paths: &[],
        serialization,
        file_version_ue4: crate::version::ue4::HIGHEST,
        file_version_ue5: crate::version::ue5::IMPORT_TYPE_HIERARCHIES,
    };
    let bytes = [2u8];
    let mut reader = Reader::new(&bytes);
    consume_known_node_tail(
        &mut reader,
        bytes.len() as u64,
        &context,
        "/Script/BlueprintGraph.K2Node_DynamicCast",
        "/exports/0/pins",
    )
    .expect("PureState should consume exactly one byte");
    assert_eq!(reader.pos(), 1);

    let mut truncated = Reader::new(&[]);
    let diagnostic = consume_known_node_tail(
        &mut truncated,
        0,
        &context,
        "/Script/BlueprintGraph.K2Node_DynamicCast",
        "/exports/0/pins",
    )
    .expect_err("missing PureState must be explicit");
    assert_eq!(diagnostic.code, "dynamic_cast_pure_state_truncated");
}

#[test]
fn pin_reference_array_accepts_compact_null_entries() {
    let mut data = Vec::new();
    push_i32(&mut data, 3);
    push_i32(&mut data, 1);
    push_i32(&mut data, 1);
    push_i32(&mut data, 1);
    let mut reader = Reader::new(&data);
    let refs = parse_pin_ref_array(&mut reader).expect("null PinRefs only occupy bool32 values");
    assert!(refs.is_empty());
    assert_eq!(reader.pos(), data.len() as u64);
}

#[test]
fn pin_reference_array_rejects_truncated_non_null_entry() {
    let mut data = Vec::new();
    push_i32(&mut data, 1);
    push_i32(&mut data, 0); // non-null
    push_i32(&mut data, 7); // node index, missing Guid
    let mut reader = Reader::new(&data);
    let error = parse_pin_ref_array(&mut reader).expect_err("non-null PinRef requires a Guid");
    assert!(!format!("{error:#}").contains("pin reference count out of range"));
    assert!(
        reader.pos() > 4,
        "the entry must be inspected after count validation"
    );
}

#[test]
fn logic_graphs_group_by_outer_and_never_emit_cross_graph_edges() {
    let base = Package::parse(&build_minimal_package()).unwrap();
    let mut exports = vec![
        test_export(0, 0, 0, 0),
        test_export(1, 0, 0, 0),
        test_export(2, 0, 0, 0),
        test_export(3, 0, 0, 0),
        test_export(4, 0, 0, 0),
    ];
    exports[2].outer_index.0 = 1;
    exports[3].outer_index.0 = 1;
    exports[4].outer_index.0 = 2;
    let package = Package {
        summary: base.summary,
        names: NameMap {
            names: vec![
                "GraphA".into(),
                "GraphB".into(),
                "NodeA".into(),
                "NodeB".into(),
                "NodeC".into(),
            ],
        },
        imports: Vec::new(),
        exports,
        soft_object_paths: Vec::new(),
        soft_object_path_error: None,
        soft_package_references: Vec::new(),
        soft_package_reference_error: None,
    };
    let output_id = Guid([1, 2, 3, 4]);
    let input_id = Guid([5, 6, 7, 8]);
    let cross_id = Guid([9, 10, 11, 12]);
    let data_output_id = Guid([13, 14, 15, 16]);
    let data_input_id = Guid([17, 18, 19, 20]);
    let node_a = decoded_node(
        3,
        "NodeA",
        vec![
            graph_pin(output_id, 1, "exec", vec![(4, input_id), (5, cross_id)]),
            graph_pin(data_output_id, 1, "int", vec![(4, data_input_id)]),
        ],
    );
    let mut data_input = graph_pin(data_input_id, 0, "int", vec![(3, data_output_id)]);
    data_input.friendly_name = Some(serde_json::json!("Amount"));
    data_input.source_index = Some(7);
    data_input.tooltip = "Amount to add".into();
    data_input.default_value = "42".into();
    data_input.autogenerated_default_value = "0".into();
    data_input.default_text = serde_json::json!({ "source": "Forty Two" });
    let node_b = decoded_node(
        4,
        "NodeB",
        vec![
            graph_pin(input_id, 0, "exec", vec![(3, output_id)]),
            data_input,
        ],
    );
    let node_c = decoded_node(
        5,
        "NodeC",
        vec![graph_pin(cross_id, 0, "exec", vec![(3, output_id)])],
    );
    let mut sections = OutputSections::none();
    sections.pins = true;
    let report = DecodeReport {
        package: &package,
        sections,
        exports: vec![
            decoded_export(1, "GraphA", None),
            decoded_export(2, "GraphB", None),
            node_a,
            node_b,
            node_c,
        ],
        diagnostics: Vec::new(),
    };

    let typed_graphs = build_logic_graphs(&report);
    assert_eq!(typed_graphs.len(), 2);
    assert_eq!(typed_graphs[0].nodes.len(), 2);
    assert_eq!(typed_graphs[0].edges.len(), 2);
    let exec_edge = typed_graphs[0]
        .edges
        .iter()
        .find(|edge| edge.kind == EdgeKind::Exec)
        .unwrap();
    assert_eq!(exec_edge.from.node_index, 3);
    assert_eq!(exec_edge.from.pin_id, output_id.to_hex());
    assert_eq!(exec_edge.to.node_index, 4);
    assert_eq!(exec_edge.to.pin_id, input_id.to_hex());
    let data_edge = typed_graphs[0]
        .edges
        .iter()
        .find(|edge| edge.kind == EdgeKind::Data)
        .unwrap();
    assert_eq!(data_edge.from.pin_id, data_output_id.to_hex());
    assert_eq!(data_edge.to.pin_id, data_input_id.to_hex());
    let typed_data_input = &typed_graphs[0].nodes[1].pins[1];
    assert_eq!(typed_data_input.source_index, Some(7));
    assert_eq!(typed_data_input.tooltip, "Amount to add");
    assert_eq!(typed_data_input.default_value.as_deref(), Some("42"));
    assert_eq!(
        typed_data_input.autogenerated_default_value.as_deref(),
        Some("0")
    );
    assert!(matches!(
        typed_data_input.friendly_name,
        Some(crate::DecodedValue::String(ref value)) if value == "Amount"
    ));
    assert_eq!(typed_graphs[0].excluded_cross_graph_links, 1);
    let typed_round_trip: Vec<crate::LogicGraph> =
        serde_json::from_str(&serde_json::to_string(&typed_graphs).unwrap()).unwrap();
    assert_eq!(typed_round_trip, typed_graphs);

    let json = report.to_json();
    let graphs = json["graphs"].as_array().unwrap();
    assert_eq!(graphs.len(), 2);
    assert_eq!(graphs[0]["nodes"].as_array().unwrap().len(), 2);
    assert_eq!(graphs[0]["edges"].as_array().unwrap().len(), 2);
    assert_eq!(graphs[0]["edges"][0]["from"]["node_index"], 3);
    assert_eq!(graphs[0]["edges"][0]["to"]["node_index"], 4);
    assert_eq!(graphs[0]["excluded_cross_graph_links"], 1);
    assert!(
        graphs[0]["edges"]
            .as_array()
            .unwrap()
            .iter()
            .all(|edge| { edge["from"]["node_index"] != 5 && edge["to"]["node_index"] != 5 })
    );
    assert!(graphs[1]["edges"].as_array().unwrap().is_empty());
}

fn push_minimal_owned_pin(data: &mut Vec<u8>) {
    push_i32(data, 0); // no UObject guid
    push_i32(data, 1); // pin count
    push_i32(data, 0); // owning-pin entry is not null
    push_i32(data, 3); // wrapper node
    push_guid(data, 1, 2, 3, 4); // wrapper guid
    push_i32(data, 3); // owning node
    push_guid(data, 1, 2, 3, 4); // pin id
    push_raw_name(data, 0); // MyPin
    push_fstring(data, ""); // tooltip
    data.push(1); // output
    push_minimal_pin_type(data, 1, 2);
    push_fstring(data, ""); // default
    push_fstring(data, ""); // autogenerated default
    push_i32(data, 0); // default object
    push_empty_ftext(data);
    push_i32(data, 0); // linked
    push_i32(data, 0); // sub-pins
    push_i32(data, 1); // null parent
    push_i32(data, 1); // null reference pass-through
}

fn push_minimal_pin_type(data: &mut Vec<u8>, category: i32, none: i32) {
    push_raw_name(data, category);
    push_raw_name(data, none);
    push_i32(data, 0);
    data.push(0);
    push_i32(data, 0);
    push_i32(data, 0);
    push_i32(data, 0);
    push_raw_name(data, none);
    push_guid(data, 0, 0, 0, 0);
    push_i32(data, 0);
}

fn decoded_node(index: i32, name: &str, pins: Vec<Pin>) -> DecodedExport {
    decoded_export(index, name, Some(pins))
}

fn decoded_export(index: i32, name: &str, pins: Option<Vec<Pin>>) -> DecodedExport {
    DecodedExport {
        identity: DecodedExportIdentity {
            index,
            name: name.into(),
            class: "/Script/BlueprintGraph.K2Node_Test".into(),
            is_asset: false,
        },
        layout: None,
        properties: None,
        property_status: None,
        post_property_tail: None,
        object_guid: None,
        metadata: None,
        pins,
        user_defined_pins: None,
        member: None,
        rigvm_link: None,
    }
}

fn graph_pin(pin_id: Guid, direction: u8, category: &str, links: Vec<(i32, Guid)>) -> Pin {
    Pin {
        pin_id,
        name: "Pin".into(),
        friendly_name: None,
        source_index: None,
        tooltip: String::new(),
        direction,
        category: category.into(),
        sub_category: String::new(),
        sub_category_object: 0,
        default_value: String::new(),
        autogenerated_default_value: String::new(),
        default_object: 0,
        default_text: serde_json::Value::Null,
        linked_to: links
            .into_iter()
            .map(|(node_index, pin_id)| crate::pin::PinRef { node_index, pin_id })
            .collect(),
        sub_pins: Vec::new(),
        parent_pin: None,
        container_type: 0,
        value_type: None,
        is_reference: false,
        is_weak_pointer: false,
        member_parent: 0,
        member_name: String::new(),
        member_guid: Guid([0; 4]),
        is_const: false,
        is_uobject_wrapper: false,
        serialize_as_single_precision_float: false,
        persistent_guid: None,
        editor_flags: None,
        reference_pass_through: None,
    }
}
