use super::common::{build_minimal_package, push_fstring, push_u32, put_i32};
use crate::analysis::analyze_package;
use crate::graph_models::{
    GraphNode, GraphPin, GraphPinType, LogicGraph, PinContainer, PinDirection, UserDefinedGraphPin,
};
use crate::model::*;
use crate::name::NameMap;
use crate::object::{ObjectImport, PackageIndex};
use crate::package::Package;
use crate::references::build_reference_evidence;
use std::collections::BTreeMap;

fn raw_name(index: i32) -> crate::reader::RawName {
    crate::reader::RawName { index, number: 0 }
}

fn export_with_property(name: &str, value: DecodedValue) -> AssetExport {
    AssetExport {
        index: 1,
        name: "Export".into(),
        class: "/Script/Engine.Actor".into(),
        super_name: String::new(),
        template_name: String::new(),
        outer_index: 0,
        outer_name: String::new(),
        full_name: "Export".into(),
        is_asset: true,
        serialization: None,
        object_guid: None,
        property_status: None,
        properties: vec![AssetProperty {
            name: name.into(),
            type_name: "SoftObjectProperty".into(),
            array_index: 0,
            value,
            guid: None,
        }],
        metadata: None,
        member: None,
        script: None,
    }
}

fn pin_type() -> GraphPinType {
    GraphPinType {
        category: "softobject".into(),
        sub_category: String::new(),
        sub_category_object: None,
        container: PinContainer::None,
        value_type: None,
        is_reference: false,
        is_weak_pointer: false,
        is_const: false,
        is_uobject_wrapper: false,
        serialize_as_single_precision_float: false,
        member_reference: None,
    }
}

fn graph_with_pin_default(default_value: Option<String>) -> LogicGraph {
    LogicGraph {
        index: 1,
        name: "EventGraph".into(),
        full_name: "Blueprint.EventGraph".into(),
        nodes: vec![GraphNode {
            index: 2,
            name: "K2Node_MakeStruct".into(),
            class: "/Script/BlueprintGraph.K2Node_MakeStruct".into(),
            member: None,
            pins: vec![GraphPin {
                pin_id: "pin-0".into(),
                name: "Path".into(),
                friendly_name: None,
                source_index: None,
                tooltip: String::new(),
                direction: PinDirection::Input,
                pin_type: pin_type(),
                default_value,
                autogenerated_default_value: None,
                default_object: None,
                default_text: None,
                linked_to: Vec::new(),
                sub_pins: Vec::new(),
                parent_pin: None,
                reference_pass_through: None,
                persistent_guid: None,
                editor_flags: None,
            }],
            user_defined_pins: Vec::new(),
        }],
        edges: Vec::new(),
        excluded_cross_graph_links: 0,
        unresolved_links: 0,
    }
}

fn tables(assets: &[&str], soft: &[&str]) -> AssetReferences {
    AssetReferences {
        assets: assets.iter().map(|value| value.to_string()).collect(),
        scripts: vec!["/Script/Engine".into()],
        soft: soft.iter().map(|value| value.to_string()).collect(),
    }
}

fn soft_path(path: &str) -> DecodedValue {
    DecodedValue::Object(BTreeMap::from([(
        "asset_path".to_string(),
        DecodedValue::String(path.to_string()),
    )]))
}

#[test]
fn a_typed_soft_path_recorded_by_the_tables_is_confirmed_not_value_only() {
    let evidence = build_reference_evidence(
        "/Game/Self",
        &tables(&["/Game/Foo/Bar"], &[]),
        &[export_with_property(
            "Target",
            soft_path("/Game/Foo/Bar.Bar"),
        )],
        &[],
    );

    assert_eq!(evidence.value_packages, 1);
    assert_eq!(evidence.confirmed_by_tables, 1);
    assert!(evidence.value_only_packages.is_empty());
    assert_eq!(evidence.sources.property_values, 1);
}

#[test]
fn a_pin_default_string_absent_from_both_tables_is_reported_as_value_only() {
    // The case the linker tables genuinely cannot hold: an asset path typed into a
    // graph pin, loaded at runtime, and never harvested as a typed reference.
    let evidence = build_reference_evidence(
        "/Game/Self",
        &tables(&[], &[]),
        &[],
        &[graph_with_pin_default(Some(
            "/Game/Runtime/Loaded.Loaded".into(),
        ))],
    );

    assert_eq!(evidence.value_packages, 1);
    assert_eq!(evidence.confirmed_by_tables, 0);
    assert_eq!(evidence.value_only_packages, vec!["/Game/Runtime/Loaded"]);
    assert_eq!(evidence.sources.pin_default_values, 1);
    assert_eq!(evidence.sources.property_values, 0);
}

#[test]
fn table_matching_ignores_case_so_authored_paths_do_not_look_value_only() {
    let evidence = build_reference_evidence(
        "/Game/Self",
        &tables(&["/Game/Foo/Bar"], &[]),
        &[],
        &[graph_with_pin_default(Some("/game/foo/bar".into()))],
    );

    assert_eq!(evidence.confirmed_by_tables, 1);
    assert!(evidence.value_only_packages.is_empty());
}

#[test]
fn script_paths_the_package_itself_and_single_segment_text_are_not_reference_candidates() {
    let evidence = build_reference_evidence(
        "/Game/Self",
        &tables(&[], &["/Game/Self"]),
        &[
            export_with_property("Class", soft_path("/Script/Engine.Actor")),
            export_with_property("Own", soft_path("/Game/Self.Self_C")),
        ],
        // A slash-prefixed string with one segment is ordinary text, not a package.
        &[graph_with_pin_default(Some("/NotAPackage".into()))],
    );

    // `/Game/Self` is still a decoded value, so it counts and is confirmed by the
    // package's own soft reference; `/Script/...` and `/NotAPackage` are excluded.
    assert_eq!(evidence.value_packages, 1);
    assert_eq!(evidence.confirmed_by_tables, 1);
    assert!(evidence.value_only_packages.is_empty());
    assert_eq!(evidence.sources.pin_default_values, 0);
}

// A Niagara or material asset stores generated HLSL as a string property, and its
// comment lines start with `//`. Reduced naively that looks like a package path,
// which reported shader source as a missing asset reference.
#[test]
fn text_that_ue_would_reject_as_a_package_name_is_not_a_reference_candidate() {
    let evidence = build_reference_evidence(
        "/Game/Self",
        &tables(&[], &[]),
        &[
            export_with_property(
                "ShaderSource",
                DecodedValue::String(
                    "// Shader generated by Niagara HLSL Translator\n// SimStage[0] = Spawn\n"
                        .into(),
                ),
            ),
            // Same shape, but every character is legal in a long package name.
            export_with_property(
                "Real",
                DecodedValue::String("/Game/Fx/NS_Sparks.NS_Sparks".into()),
            ),
        ],
        &[],
    );

    assert_eq!(evidence.value_only_packages, vec!["/Game/Fx/NS_Sparks"]);
}

#[test]
fn user_defined_pin_defaults_are_a_reference_source() {
    let mut graph = graph_with_pin_default(None);
    graph.nodes[0].user_defined_pins = vec![UserDefinedGraphPin {
        name: "Asset".into(),
        direction: PinDirection::Input,
        pin_type: pin_type(),
        default_value: Some("/Game/Widgets/W_Popup.W_Popup".into()),
    }];

    let evidence = build_reference_evidence("/Game/Self", &tables(&[], &[]), &[], &[graph]);

    assert_eq!(evidence.value_only_packages, vec!["/Game/Widgets/W_Popup"]);
}

#[test]
fn the_cross_check_runs_only_in_the_view_that_decodes_both_sides() {
    // A package carrying one Package import and one soft package reference, so the
    // tables are non-empty in every view that reads them.
    let mut data = build_minimal_package();
    let soft_offset = data.len() as i32;
    push_fstring(&mut data, "/Game/Foo/SoftDep");
    push_u32(&mut data, 0);
    put_i32(&mut data, 132, 1);
    put_i32(&mut data, 136, soft_offset);

    let mut package = Package::parse(&data).unwrap();
    package.names = NameMap {
        names: vec![
            "/Script/CoreUObject".into(),
            "Package".into(),
            "/Game/Foo/Bar".into(),
        ],
    };
    package.imports = vec![ObjectImport {
        class_package: raw_name(0),
        class_name: raw_name(1),
        outer_index: PackageIndex(0),
        object_name: raw_name(2),
        package_name: None,
    }];

    let references = analyze_package(&package, &data, AssetView::References);
    assert_eq!(references.references.assets, vec!["/Game/Foo/Bar"]);
    assert!(
        references.reference_evidence.is_none(),
        "the references view decodes no values, so an empty cross-check would claim \
         a check that never ran"
    );

    let full = analyze_package(&package, &data, AssetView::Full);
    let evidence = full
        .reference_evidence
        .expect("the full view decodes both the tables and the values");
    // No exports and no graphs in this fixture: the cross-check ran and found
    // nothing, which is a different statement from not having run.
    assert_eq!(evidence.value_packages, 0);
    assert!(evidence.value_only_packages.is_empty());
}
