mod common;

use cc_uax::name::NameMap;
use cc_uax::pin::{
    PinSerCtx, container_type_label, direction_label, parse_node_pins, parse_node_pins_report,
};
use cc_uax::property::{ParseCtx, parse_properties};
use cc_uax::reader::Reader;
use common::*;

#[test]
fn node_pin_array_decodes() {
    let names = NameMap {
        names: vec![
            "MyPin".to_string(),
            "exec".to_string(),
            "None".to_string(),
            "MemberFunc".to_string(),
        ],
    };

    let mut d = Vec::new();

    push_i32(&mut d, 0); // PossiblySerializeObjectGuid presence = false

    push_i32(&mut d, 1); // pin count

    // Owning-pin element prelude: null flag + wrapper node index + wrapper pin guid.

    push_i32(&mut d, 0);

    push_i32(&mut d, 3);

    push_guid(&mut d, 1, 2, 3, 4);

    // Pin body (filter_editor_only = false, no source index, no wrapper flags).

    push_i32(&mut d, 3); // owning node

    push_guid(&mut d, 1, 2, 3, 4); // pin id

    push_raw_name(&mut d, 0); // MyPin

    push_empty_ftext(&mut d); // friendly name

    push_fstring(&mut d, ""); // tooltip

    d.push(1); // direction = output

    push_raw_name(&mut d, 1); // pin type category "exec"

    push_raw_name(&mut d, 2); // pin type sub_category

    push_i32(&mut d, 0); // sub_category_object

    d.push(0); // container type = none

    push_i32(&mut d, 1); // bIsReference

    push_i32(&mut d, 1); // bIsWeakPointer

    push_i32(&mut d, -4); // member reference parent

    push_raw_name(&mut d, 3); // member reference name

    push_guid(&mut d, 4, 3, 2, 1); // member reference guid

    push_i32(&mut d, 1); // bIsConst

    push_i32(&mut d, 1); // bIsUObjectWrapper

    push_i32(&mut d, 1); // bSerializeAsSinglePrecisionFloat

    push_fstring(&mut d, ""); // default value

    push_fstring(&mut d, ""); // autogenerated default

    push_i32(&mut d, 0); // default object

    push_empty_ftext(&mut d); // default text

    push_i32(&mut d, 1); // LinkedTo count

    push_i32(&mut d, 0); // reference: not null

    push_i32(&mut d, 2); // referenced node index

    push_guid(&mut d, 9, 9, 9, 9); // referenced pin guid

    push_i32(&mut d, 0); // SubPins count

    push_i32(&mut d, 1); // parent pin = null

    push_i32(&mut d, 0); // reference passthrough = not null

    push_i32(&mut d, 5); // pass-through node index

    push_guid(&mut d, 8, 8, 8, 8); // pass-through pin guid

    push_guid(&mut d, 6, 7, 8, 9); // persistent guid (editor-only block)

    push_u32(&mut d, (1 << 0) | (1 << 3) | (1 << 5)); // editor bitfield

    let ctx = ParseCtx {
        names: &names,

        resolve_object: &|_idx: i32| serde_json::Value::Null,

        pins: PinSerCtx::default(),

        soft_object_paths: &[],

        niagara_version: -1,

        fortnite_main_version: -1,

        file_version_ue4: cc_uax::version::ue4::HIGHEST,

        file_version_ue5: cc_uax::version::ue5::PROPERTY_TAG_COMPLETE_TYPE_NAME,
    };

    let vc = PinSerCtx {
        has_uobject_wrapper: true,

        has_single_precision_float: true,

        ..PinSerCtx::default()
    };

    let mut r = Reader::new(&d);

    let pins = parse_node_pins(&mut r, d.len() as u64, &ctx, &vc).expect("pins should parse");

    assert_eq!(r.pos(), d.len() as u64, "pin array must consume all bytes");

    assert_eq!(pins.len(), 1);

    let p = &pins[0];

    assert_eq!(p.name, "MyPin");

    assert_eq!(direction_label(p.direction), "output");

    assert_eq!(p.category, "exec");

    assert_eq!(container_type_label(p.container_type), "none");

    assert!(p.is_reference);

    assert!(p.is_weak_pointer);

    assert_eq!(p.member_parent, -4);

    assert_eq!(p.member_name, "MemberFunc");

    assert_eq!(p.member_guid.to_hex(), "00000004000000030000000200000001");

    assert!(p.is_const);

    assert!(p.is_uobject_wrapper);

    assert!(p.serialize_as_single_precision_float);

    assert_eq!(p.pin_id.to_hex(), "00000001000000020000000300000004");

    assert_eq!(p.linked_to.len(), 1);

    assert_eq!(p.linked_to[0].node_index, 2);

    assert!(p.sub_pins.is_empty());

    assert!(p.parent_pin.is_none());

    let pass_through = p.reference_pass_through.as_ref().unwrap();

    assert_eq!(pass_through.node_index, 5);

    assert_eq!(
        pass_through.pin_id.to_hex(),
        "00000008000000080000000800000008"
    );

    assert_eq!(
        p.persistent_guid.unwrap().to_hex(),
        "00000006000000070000000800000009"
    );

    let flags = p.editor_flags.as_ref().unwrap();

    assert!(flags.hidden);

    assert!(!flags.not_connectable);

    assert!(!flags.default_value_read_only);

    assert!(flags.default_value_ignored);

    assert!(!flags.advanced_view);

    assert!(flags.orphaned_pin);
}

#[test]
fn node_pin_parse_failure_reports_diagnostic() {
    let names = NameMap {
        names: vec!["None".to_string()],
    };
    let mut d = Vec::new();
    push_i32(&mut d, 0); // no UObject guid
    push_i32(&mut d, 10_000); // invalid pin count

    let ctx = ParseCtx {
        names: &names,
        resolve_object: &|_idx: i32| serde_json::Value::Null,
        pins: PinSerCtx::default(),
        soft_object_paths: &[],
        niagara_version: -1,
        fortnite_main_version: -1,
        file_version_ue4: cc_uax::version::ue4::HIGHEST,
        file_version_ue5: cc_uax::version::ue5::PROPERTY_TAG_COMPLETE_TYPE_NAME,
    };

    let mut r = Reader::new(&d);
    let err = parse_node_pins_report(
        &mut r,
        d.len() as u64,
        &ctx,
        &PinSerCtx::default(),
        "/exports/0/pins",
    )
    .expect_err("invalid pin stream should report a diagnostic");

    assert_eq!(err.code, "pin_parse_failed");
    assert_eq!(err.path, "/exports/0/pins");
    assert!(err.message.contains("pin count out of range"));
    assert_eq!(err.offset, Some(8));
    assert_eq!(r.pos(), 0, "failed pin parse must rewind to start");
}

#[test]
fn edgraph_pin_type_map_container_decodes() {
    // Map-container pin types carry an FEdGraphTerminalType (map value type) between

    // ContainerType and bIsReference.

    let names = NameMap {
        names: vec![
            "PinType".to_string(),        // 0
            "StructProperty".to_string(), // 1
            "EdGraphPinType".to_string(), // 2
            "int".to_string(),            // 3
            "string".to_string(),         // 4
            "None".to_string(),           // 5
        ],
    };

    let mut value = Vec::new();

    push_raw_name(&mut value, 3); // category = "int"

    push_raw_name(&mut value, 5); // sub_category

    push_i32(&mut value, -4); // sub_category_object

    value.push(3); // container_type = Map

    push_raw_name(&mut value, 4); // terminal category = "string"

    push_raw_name(&mut value, 5); // terminal sub_category

    push_i32(&mut value, 0); // terminal sub_category_object

    push_i32(&mut value, 1); // terminal bIsConst

    push_i32(&mut value, 1); // terminal bIsWeakPointer

    push_i32(&mut value, 1); // terminal bIsUObjectWrapper (wrapper flag enabled)

    push_i32(&mut value, 1); // bIsReference

    push_i32(&mut value, 1); // bIsWeakPointer

    push_i32(&mut value, -8); // member reference parent

    push_raw_name(&mut value, 4); // member reference name

    push_guid(&mut value, 1, 1, 2, 2); // member reference guid

    push_i32(&mut value, 1); // bIsConst

    push_i32(&mut value, 1); // bIsUObjectWrapper

    push_i32(&mut value, 1); // bSerializeAsSinglePrecisionFloat

    let d = build_struct_property(2, 5, &value);

    let ctx = ParseCtx {
        names: &names,

        resolve_object: &|idx: i32| serde_json::json!({ "index": idx }),

        pins: PinSerCtx {
            filter_editor_only: false,

            has_source_index: false,

            has_uobject_wrapper: true,

            has_single_precision_float: true,
        },

        soft_object_paths: &[],

        niagara_version: -1,

        fortnite_main_version: -1,

        file_version_ue4: cc_uax::version::ue4::HIGHEST,

        file_version_ue5: cc_uax::version::ue5::PROPERTY_TAG_COMPLETE_TYPE_NAME,
    };

    let mut r = Reader::new(&d);

    let entries = parse_properties(&mut r, &ctx, d.len() as u64);

    assert_eq!(entries.len(), 1);

    let v = &entries[0].value;

    assert_eq!(v["category"].as_str(), Some("int"));

    assert_eq!(v["sub_category_object"]["index"].as_i64(), Some(-4));

    assert_eq!(v["container_type"].as_str(), Some("map"));

    assert_eq!(v["value_type"]["category"].as_str(), Some("string"));

    assert_eq!(v["value_type"]["is_const"].as_bool(), Some(true));

    assert_eq!(v["value_type"]["is_weak_pointer"].as_bool(), Some(true));

    assert_eq!(v["value_type"]["is_uobject_wrapper"].as_bool(), Some(true));

    assert_eq!(v["is_reference"].as_bool(), Some(true));

    assert_eq!(v["is_weak_pointer"].as_bool(), Some(true));

    assert_eq!(v["member_reference"]["parent"]["index"].as_i64(), Some(-8));

    assert_eq!(v["member_reference"]["name"].as_str(), Some("string"));

    assert_eq!(
        v["member_reference"]["guid"].as_str(),
        Some("00000001000000010000000200000002")
    );

    assert_eq!(v["is_const"].as_bool(), Some(true));

    assert_eq!(v["is_uobject_wrapper"].as_bool(), Some(true));

    assert_eq!(
        v["serialize_as_single_precision_float"].as_bool(),
        Some(true)
    );
}
