use crate::property::{ParseCtx, parse_text};
use crate::reader::{Guid, Reader};
use crate::summary::PackageFileSummary;
use crate::version::custom;
use anyhow::{Result, bail};

const MAX_PIN_COUNT: i32 = 4096;
const CONTAINER_TYPE_MAP: u8 = 3;
const PIN_DIRECTION_INPUT: u8 = 0;

pub struct PinSerCtx {
    pub filter_editor_only: bool,
    pub has_source_index: bool,
    pub has_uobject_wrapper: bool,
    pub has_single_precision_float: bool,
}

impl PinSerCtx {
    pub fn from_summary(s: &PackageFileSummary) -> Self {
        let main = s
            .custom_version(custom::UE5_MAIN_STREAM_OBJECT_VERSION)
            .unwrap_or(-1);
        let release = s
            .custom_version(custom::RELEASE_OBJECT_VERSION)
            .unwrap_or(-1);
        let ue5_release = s
            .custom_version(custom::UE5_RELEASE_STREAM_OBJECT_VERSION)
            .unwrap_or(-1);
        PinSerCtx {
            filter_editor_only: s.filter_editor_only(),
            has_source_index: main >= custom::EDGRAPH_PIN_SOURCE_INDEX,
            has_uobject_wrapper: release >= custom::PIN_TYPE_INCLUDES_UOBJECT_WRAPPER_FLAG,
            has_single_precision_float: ue5_release >= custom::SERIALIZE_FLOAT_PIN_SINGLE_PRECISION,
        }
    }
}

#[derive(Debug, Clone)]
pub struct PinRef {
    pub node_index: i32,
    pub pin_id: Guid,
}

#[derive(Debug, Clone)]
pub struct Pin {
    pub pin_id: Guid,
    pub name: String,
    pub direction: u8,
    pub category: String,
    pub sub_category: String,
    pub sub_category_object: i32,
    pub default_value: String,
    pub default_object: i32,
    pub linked_to: Vec<PinRef>,
    pub sub_pins: Vec<PinRef>,
    pub parent_pin: Option<PinRef>,
}

pub fn direction_label(direction: u8) -> &'static str {
    if direction == PIN_DIRECTION_INPUT {
        "input"
    } else {
        "output"
    }
}

pub fn parse_node_pins(
    r: &mut Reader,
    end: u64,
    ctx: &ParseCtx,
    vc: &PinSerCtx,
) -> Option<Vec<Pin>> {
    let start = r.pos();
    match parse_pins_inner(r, end, ctx, vc) {
        Ok(pins) if r.pos() <= end => Some(pins),
        _ => {
            let _ = r.seek(start);
            None
        }
    }
}

fn parse_pins_inner(r: &mut Reader, end: u64, ctx: &ParseCtx, vc: &PinSerCtx) -> Result<Vec<Pin>> {
    let has_object_guid = r.read_bool32()?;
    if has_object_guid {
        let _object_guid = r.read_guid()?;
    }
    let count = r.read_i32()?;
    if !(0..=MAX_PIN_COUNT).contains(&count) {
        bail!("pin count out of range: {count}");
    }
    let mut pins = Vec::with_capacity(count as usize);
    for _ in 0..count {
        if r.read_bool32()? {
            bail!("owning pin entry is null");
        }
        let _wrapper_node = r.read_i32()?;
        let _wrapper_guid = r.read_guid()?;
        let pin = parse_pin(r, ctx, vc)?;
        pins.push(pin);
        if r.pos() > end {
            bail!("pin region overrun");
        }
    }
    Ok(pins)
}

fn parse_pin(r: &mut Reader, ctx: &ParseCtx, vc: &PinSerCtx) -> Result<Pin> {
    let _owning_node = r.read_i32()?;
    let pin_id = r.read_guid()?;
    let name = ctx.names.resolve_raw(r.read_raw_name()?);
    if !vc.filter_editor_only {
        let _friendly_name = parse_text(r, ctx.names, 0)?;
    }
    if vc.has_source_index {
        let _source_index = r.read_i32()?;
    }
    let _tooltip = r.read_fstring()?;
    let direction = r.read_u8()?;
    let (category, sub_category, sub_category_object) = parse_pin_type(r, ctx, vc)?;
    let default_value = r.read_fstring()?;
    let _autogenerated_default = r.read_fstring()?;
    let default_object = r.read_i32()?;
    let _default_text = parse_text(r, ctx.names, 0)?;
    let linked_to = parse_pin_ref_array(r)?;
    let sub_pins = parse_pin_ref_array(r)?;
    let parent_pin = parse_pin_ref(r)?;
    let _ref_passthrough = parse_pin_ref(r)?;
    if !vc.filter_editor_only {
        let _persistent_guid = r.read_guid()?;
        let _bitfield = r.read_u32()?;
    }
    Ok(Pin {
        pin_id,
        name,
        direction,
        category,
        sub_category,
        sub_category_object,
        default_value,
        default_object,
        linked_to,
        sub_pins,
        parent_pin,
    })
}

fn parse_pin_type(r: &mut Reader, ctx: &ParseCtx, vc: &PinSerCtx) -> Result<(String, String, i32)> {
    let category = ctx.names.resolve_raw(r.read_raw_name()?);
    let sub_category = ctx.names.resolve_raw(r.read_raw_name()?);
    let sub_category_object = r.read_i32()?;
    let container_type = r.read_u8()?;
    if container_type == CONTAINER_TYPE_MAP {
        parse_terminal_type(r, vc)?;
    }
    let _is_reference = r.read_bool32()?;
    let _is_weak_pointer = r.read_bool32()?;
    let _member_parent = r.read_i32()?;
    let _member_name = r.read_raw_name()?;
    let _member_guid = r.read_guid()?;
    let _is_const = r.read_bool32()?;
    if vc.has_uobject_wrapper {
        let _is_uobject_wrapper = r.read_bool32()?;
    }
    if vc.has_single_precision_float {
        let _single_precision = r.read_bool32()?;
    }
    Ok((category, sub_category, sub_category_object))
}

fn parse_terminal_type(r: &mut Reader, vc: &PinSerCtx) -> Result<()> {
    let _category = r.read_raw_name()?;
    let _sub_category = r.read_raw_name()?;
    let _sub_category_object = r.read_i32()?;
    let _is_const = r.read_bool32()?;
    let _is_weak_pointer = r.read_bool32()?;
    if vc.has_uobject_wrapper {
        let _is_uobject_wrapper = r.read_bool32()?;
    }
    Ok(())
}

fn parse_pin_ref_array(r: &mut Reader) -> Result<Vec<PinRef>> {
    let count = r.read_i32()?;
    if count < 0 || count as u64 > r.remaining() {
        bail!("pin reference count out of range: {count}");
    }
    let mut refs = Vec::new();
    for _ in 0..count {
        if let Some(pin_ref) = parse_pin_ref(r)? {
            refs.push(pin_ref);
        }
    }
    Ok(refs)
}

fn parse_pin_ref(r: &mut Reader) -> Result<Option<PinRef>> {
    if r.read_bool32()? {
        return Ok(None);
    }
    let node_index = r.read_i32()?;
    let pin_id = r.read_guid()?;
    Ok(Some(PinRef { node_index, pin_id }))
}
